### ISSUE TITLE
PKUMMD missing file

### ISSUE THREAD

**Issue by EdwardTse9944** [JHang2020/HiCLR#1]
Hi, thank you so much for your excellent work.
I noticed there existed a pkummd_gendata process and it needs missing files for both pkummdv1 and pkummdv2.
Is there any possibility that you could provide these two files?
Highly appreciate if you could do so.

**Comment by JHang2020** [comment]
Hello~
For PKUMMD dataset, there are no missing file lists. You can set the file to an empty .txt file (or None) and process the data.

**Comment by EdwardTse9944** [comment]
> Hello~ For PKUMMD dataset, there are no missing file lists. You can set the file to an empty .txt file (or None) and process the data.

thank you so much for your reply, appreciate it.
